enhancement(events): send dm to private channel on event creation
f1v/hrbot pull request #187
Opened 2021-06-23 20:50 UTC by PatrickDohn

#### Summary

_Enumerate and describe your changes_

- On event creation send message to private channel 

#### Checklist

_Double check list and complete these actions before merge_

- [ ] PR title is in format `TYPE(scope): description`
- [ ] Link PR to Issue (if any issues are related)

2021-06-24 14:43 UTC, PatrickDohn commented on src/app.js
> +    `;
Remove end date

2021-06-24 14:44 UTC, PatrickDohn commented on src/app.js
> +    `;
remove new line

2021-06-24 14:55 UTC, davidholyko commented on src/app.js
> +    let text = `
text should match exactly

https://user-images.githubusercontent.com/20917792/122936915-8b653c00-d33f-11eb-963c-6c84a4c70119.png

2021-06-24 14:57 UTC, davidholyko commented on src/constants.js
> +  SLACK_CHANNEL_ID: 'C026CQER9PT',
make a SLACK namespace

```
SLACK: {
  PTO_CHANNEL_ID: 'abc',
}

```

2021-06-24 18:42 UTC, PatrickDohn commented on src/constants.js
> +
channel id for the private channel where all event requests will be sent

2021-06-24 18:43 UTC, PatrickDohn commented on src/helpers/helpers.js
> +
parseText is used to handle all sick vacation types and return the correct response block to the private channel.

2021-06-24 20:06 UTC, PatrickDohn commented on src/helpers/helpers.js
> +    }`,
startDate === undefined is used to catch the single day events which have no startDate or endDate so if they are undefined set them to the current day.

2021-06-24 20:07 UTC, PatrickDohn commented on src/constants.js
> +  SLACK_CHANNEL_ID: 'C026CQER9PT',
fixed

2021-06-24 21:36 UTC, davidholyko commented on src/constants.js
> +const SLACK = {
should be a RESOURCE

https://github.com/f1v/hrbot/blob/2ef7bede5a6332b2e809a2f1efd5a7c3afd9a385/src/constants.js#L1

2021-06-24 21:37 UTC, davidholyko commented on src/helpers/helpers.js
> +  let arr = [
`const`, rename `arr` too something more descriptive

2021-06-24 21:38 UTC, davidholyko commented on src/utils/googleCalendarUtil.js
> -    const holidayList = _.map(eventList, (holiday) => {
is this deletion correct?

2021-06-24 21:38 UTC, davidholyko commented on src/helpers/helpers.js
> +const parseText = ({ email, startDate, endDate, dateRange, request }) => {
add `jsDoc`

2021-06-24 23:48 UTC, PatrickDohn commented on src/utils/googleCalendarUtil.js
> -    const holidayList = _.map(eventList, (holiday) => {
This was in my last PR we removed it and it wasnt on my new branch but when I pushed up the first time it showed up.

2021-06-25 00:29 UTC, PatrickDohn commented on src/helpers/helpers.js
> +const parseText = ({ email, startDate, endDate, dateRange, request }) => {
Fixed

2021-06-25 00:30 UTC, PatrickDohn commented on src/helpers/helpers.js
> +  let arr = [
fixed

2021-06-25 00:30 UTC, PatrickDohn commented on src/constants.js
> +const SLACK = {
Fixed

2021-06-25 13:37 UTC, davidholyko commented on src/constants.js
> +const SLACK = {
doesnt seem to be what I had in mind

2021-06-25 14:42 UTC, davidholyko commented on src/helpers/helpers.js
> + * @param {String}
This is incorrect type

2021-06-28 14:17 UTC, davidholyko commented on src/app.js
> +    chat.postMessage({ channel: PTO_CHANNEL_ID, text });
send a block instead of text

2021-06-28 14:33 UTC, davidholyko commented on src/constants.js
> +    PTO_CHANNEL_ID: 'C026CQER9PT',
TODO:  replace  with  actual ID

2021-06-28 14:35 UTC, davidholyko commented on src/helpers/helpers.js
> +    `Description: ${request ? request : 'Vacation'}, ${dateRange ? dateRange : ''}`,
this will work but it doesn't exactly look right.

what are the expected values of `request`? is it only specific values or do you want the developer to be able to put anything

2021-06-28 14:47 UTC, PatrickDohn commented on src/helpers/helpers.js
> +    `Description: ${request ? request : 'Vacation'}, ${dateRange ? dateRange : ''}`,
request is Sick or Vacation when you use the single day vacation request. When you do a future vacation there is no 'Request' so thats why request gets is put in that conditional to catch the future event.

2021-06-28 14:48 UTC, PatrickDohn commented on src/constants.js
> +    PTO_CHANNEL_ID: 'C026CQER9PT',
That is the actual id of the private channel?

2021-06-28 15:58 UTC, davidholyko requested changes
Waiting on correct channel ID.

2021-06-28 16:29 UTC, davidholyko approved these changes

2021-06-28 16:30 UTC, merged